apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: users
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: internal
    spec:
      serviceAccountName: firestore-users-service@mouth-metrics.iam.gserviceaccount.com
      containers:
        - image: asia-southeast1-docker.pkg.dev/mouth-metrics/users-service-repo/users-service
          ports:
            - containerPort: 8080
