apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: users
  annotations:
    run.googleapis.com/location: asia-southeast1
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/ingress: all
    spec:
      containers:
        - ports:
            - containerPort: 8080
